# Generated by Django 3.2 on 2021-08-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('upc', models.BigIntegerField(db_index=True, unique=True, verbose_name='upc')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.servicecategory', verbose_name='category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='item.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Item line',
                'verbose_name_plural': 'Item lines',
                'db_table': 'item_line',
            },
        ),
    ]
