# Generated by Django 3.2 on 2021-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.BigIntegerField(db_index=True, editable=False, unique=True, verbose_name='upc'),
        ),
    ]
