# Generated by Django 3.2 on 2021-09-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_rename_user_customeraddress_customer_user'),
        ('gateway', '0001_initial'),
        ('cart', '0002_remove_cart_invoice'),
        ('accounts', '0002_auto_20210831_0046'),
        ('payment', '0002_alter_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cart',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='cart.cart', verbose_name='cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=64, verbose_name='authority'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gateway.gateway', verbose_name='gateway'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_log',
            field=models.TextField(blank=True, verbose_name='logs'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='address.customeraddress', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.invoice', verbose_name='invoice'),
        ),
    ]
