# Generated by Django 3.2 on 2021-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='phone number'),
        ),
    ]
