# Generated by Django 3.2 on 2021-08-28 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'saturday'), (1, 'sunday'), (2, 'monday'), (3, 'tuesday'), (4, 'wednesday'), (5, 'thursday'), (6, 'friday')], verbose_name='day')),
                ('open_time', models.DateTimeField(verbose_name='open time')),
                ('close_time', models.DateTimeField(verbose_name='close time')),
                ('close_day', models.BooleanField(blank=True, null=True, verbose_name='close day')),
            ],
            options={
                'verbose_name': 'AvailableTime',
                'verbose_name_plural': 'AvailableTimes',
                'db_table': 'available_time',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(0, 'restaurant'), (1, 'cafe'), (2, 'confectionery'), (3, 'supermarket')], verbose_name='service type')),
                ('minimum_purchase', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='minimum purchase')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='address.address', verbose_name='address')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.serviceprovider', verbose_name='service provider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=35, verbose_name='slug')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'ServiceCategory',
                'verbose_name_plural': 'ServiceCategories',
                'db_table': 'service_category',
            },
        ),
        migrations.CreateModel(
            name='ServiceAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.availabletime', verbose_name='available time')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'ServiceAvailableTime',
                'verbose_name_plural': 'ServiceAvailableTimes',
                'db_table': 'service_available_time',
            },
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='address.area', verbose_name='area')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'DeliveryArea',
                'verbose_name_plural': 'DeliveryAreas',
                'db_table': 'delivery_area',
            },
        ),
    ]
