# Generated by Django 3.2 on 2021-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceavailabletime',
            name='available_time',
        ),
        migrations.AddField(
            model_name='serviceavailabletime',
            name='close_time',
            field=models.TimeField(null=True, verbose_name='close time'),
        ),
        migrations.AddField(
            model_name='serviceavailabletime',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'saturday'), (1, 'sunday'), (2, 'monday'), (3, 'tuesday'), (4, 'wednesday'), (5, 'thursday'), (6, 'friday')], null=True, verbose_name='day'),
        ),
        migrations.AddField(
            model_name='serviceavailabletime',
            name='is_close',
            field=models.BooleanField(blank=True, null=True, verbose_name='close day'),
        ),
        migrations.AddField(
            model_name='serviceavailabletime',
            name='open_time',
            field=models.TimeField(null=True, verbose_name='open time'),
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
