# Generated by Django 3.2 on 2021-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210902_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceavailabletime',
            options={'ordering': ('day',), 'verbose_name': 'ServiceAvailableTime', 'verbose_name_plural': 'ServiceAvailableTimes'},
        ),
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='service/banner', verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='service/logo', verbose_name='logo'),
        ),
    ]
