# Generated by Django 3.2 on 2021-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210902_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('created_time',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='service/banners/', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='service/logos/', verbose_name='logo'),
        ),
    ]
