# Generated by Django 3.2 on 2021-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210902_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
    ]
