# Generated by Django 3.2 on 2021-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('floor', models.SmallIntegerField(verbose_name='floor')),
                ('plaque', models.SmallIntegerField(verbose_name='plaque')),
            ],
            options={
                'verbose_name': 'CustomerAddress',
                'verbose_name_plural': 'CustomerAddresses',
                'db_table': 'customer_address',
            },
        ),
        migrations.CreateModel(
            name='ServiceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('floor', models.SmallIntegerField(verbose_name='floor')),
                ('plaque', models.SmallIntegerField(verbose_name='plaque')),
            ],
            options={
                'verbose_name': 'ServiceAddress',
                'verbose_name_plural': 'ServiceAddresses',
                'db_table': 'service_address',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
