# Generated by Django 3.2 on 2021-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210830_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='alley',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceaddress',
            name='alley',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceaddress',
            name='street',
            field=models.TextField(blank=True),
        ),
    ]
