# Generated by Django 3.2 on 2021-08-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20210830_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='user',
            new_name='customer_user',
        ),
    ]
