# Generated by Django 3.2 on 2021-09-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210831_0046'),
        ('payment', '0003_auto_20210912_1657'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer', verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='payment.invoice', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'preparing food'), (0, 'sending')], default=0, verbose_name='status'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
