# Generated by Django 3.2 on 2021-09-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
        ('order', '0005_alter_order_status'),
    ]

    operations = [
    ]
